spring.application.name=ferrecloud

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ferrecloud

server.port=8080

spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG